### ISSUE TITLE
Finalize travis CI

### ISSUE THREAD

**Issue by constantinius** [EOxServer/eoxserver#409]
- [ ] Test multiple Python/Django versions
- [ ] Test with multiple DBMSs (spatialite/postGIS)
- [ ] Build and deploy docker containers
- [ ] What about OSs (CentOS, Ubuntu)

**Comment by Schpidi** [comment]
# EOxServer v1.0 Baseline

This post is an (ambitioned) roadmap for the next EOxServer release

## Operating System

To support the ESA technical baseline, EOxServer needs to run on CentOS 7, so this will be our main target. We need to use SCLs to enable newer versions of Python and its dependencies (Apache mod_wsgi, etc...) (https://www.softwarecollections.org/en/scls/rhscl/rh-python36/)

We will also support Ubuntu 18.04, as this is also the version used in OSGeo-Live.

## Python

Since support for Python 2 will end with 2019 it is best to switch to Python 3 and support 2.7 on a best effort basis

## Django

The current LTS version is 2.2 (https://www.djangoproject.com/download/) which will be supported until 2022. This version requires Python 3. Again, on a best effort basis we will try to support the last LTS version 1.11 where the support will end in April 2020.

## Databases

Just as before, we will support and test the two main databases PostgreSQL (PostGIS) and SQLite (Spatialite). We do not specify a version and just take what is available.

## CI

As our Jenkins instance is not functional anymore, we will fully switch to Travis. The build matrix will be adapted to reflect the above mentioned combinations of Operating System, Python, and Django.

Additionally we will use the continuous deployment features to build Docker images, RPMs, Python wheels and upload them to the appropriate places when building tagged commits.

**Comment by Schpidi** [comment]
Can we please add a tag to the docker image like `1.0` that is always assigned to the latest release int he 1.0 line? This would come in handy in our docker-compose setups.

**Comment by constantinius** [comment]
We should branch off the 1.0 version anyhow. Then we can build images and tag them accordingly. I just added a :master tag for the latest push on the master branch.
